sudo: false
language: cpp

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.cache/yarn

notifications:
  email: false
  webhooks:
    - https://vscode-probot.westus.cloudapp.azure.com:7890/travis/notifications
    - https://vscode-test-probot.westus.cloudapp.azure.com:7890/travis/notifications

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0
      - libx11-dev
      - libxkbfile-dev
      - libsecret-1-dev

before_install:
  - export GITHUB_TOKEN=$PUBLIC_GITHUB_TOKEN
  - git submodule update --init --recursive
  - nvm install 10.16.0
  - nvm use 10.16.0
  - npm i -g yarn

install:
  - yarn

script:
  - ./scripts/test.sh
  - ./scripts/test-integration.sh

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then node_modules/.bin/coveralls < .build/coverage/lcov.info; fi

matrix:
  include:
    - os: linux
      env: label=hygiene
      script: node_modules/.bin/gulp hygiene
      after_success: skip
